name: Añadir nuevo tenant

on: 
    workflow_dispatch:
        inputs:
            tenantName:
                description: 'Nombre del nuevo tenant'
                required: true
                default: ''
            tenantId:
                description: 'Id del nuevo tenant'
                required: true
                default: ''

jobs:
  nuevoTenant:
    runs-on: windows-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{secrets.ghTokenWorkflow}}
          fetch-depth: 0
      - name: añadir Tenant
        run: |
          $tenantName = '${{github.event.inputs.tenantName}}'
          $tenantId = '${{github.event.inputs.tenantId}}'
          $data = Get-Content ./.github/scripts/environmentManagement.ps1
          $startIndex = ($data | Select-String -Pattern '^\$tenants.*$').LineNumber
          $data[$startIndex] += "`n`t @{name = '$tenantName'; tenantID = '$tenantId'; clientID = `$clientID; clientSecret= `$clientSecret}"
      
      - name: Commit changes
        run: |
          git config --global user.name "${{github.actor}}[bot]"
          git config --global user.email "${{github.actor}}[bot]@users.noreply.github.com"
          git add .
          git commit -m "Añadido nuevo tenant $tenantName"