name: A침adir nuevo tenant

on: 
    workflow_dispatch:
        inputs:
            tenantName:
                description: 'Nombre del nuevo tenant'
                required: true
                default: ''
            tenantId:
                description: 'Id del nuevo tenant'
                required: true
                default: ''

jobs:
  nuevoTenant:
    runs-on: windows-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{secrets.ghTokenWorkflow}}
          fetch-depth: 0
      - name: a침adir Tenant
        run: |
          $tenantName = '${{github.event.inputs.tenantName}}'
          $tenantId = '${{github.event.inputs.tenantId}}'
          if (-not ($tenantID -match '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'){
              Write-Error "El tenantId no es un GUID v치lido"
              exit 1
          }
          $data = Get-Content ./.github/scripts/environmentManagement.ps1
          $startIndex = ($data | Select-String -Pattern '^\$tenants.*$').LineNumber
          $data[$startIndex] += "`n`t @{name = '$tenantName'; tenantID = '$tenantId'; clientID = `$clientID; clientSecret= `$clientSecret}"
          $data | Set-Content ./.github/scripts/envirnomentManagement.ps1

      - name: Commit changes
        run: |
          git config --global user.name "${{github.actor}}[bot]"
          git config --global user.email "${{github.actor}}[bot]@users.noreply.github.com"
          git add .
          git commit -m "A침adido nuevo tenant $tenantName"
          git push