name: Test
on:
  workflow_dispatch:
    

jobs:
  build:
    runs-on: windows-latest
    env:
      VAULTNAME: ${{secrets.KEYVAULTNAME}}  
      GH_TOKEN: ${{secrets.ghTokenWorkflow}}
      
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{secrets.ghTokenWorkflow}}

      - name: Obtener appName
        run: | 
          $appName= Split-Path ${{github.repository}} -Leaf
          $workspace = $env:GITHUB_WORKSPACE
          Write-Host "-------------- WORKSPACE: $workspace"
          Write-Host "-------------- NAME: $appName"
          Write-Host "-------------- AKV: $env:VAULTNAME"
        
      # - name: Descargar BcContainerHelper y obtener appinfo
      #   shell: powershell
      #   run: |
      #     $ALGoHelperPath = "$([System.IO.Path]::GetTempFileName()).ps1"
      #     $webClient = New-Object System.Net.WebClient
      #     $webClient.DownloadFile('https://raw.githubusercontent.com/microsoft/AL-Go-Actions/v7.2/AL-Go-Helper.ps1', $ALGoHelperPath)
      #     . $ALGoHelperPath
      #     DownloadAndImportBcContainerHelper
      #     .github/scripts/ghtokenrotation.ps1 -keyvaultname $env:VAULTNAME -action 'environment'
      
      # - name: Ejecutar test
      #   shell: powershell
      #   run: |
      #     .github/scripts/test.ps1

      - name: Get-BcPubishedApp
        shell: powershell
        run: |
          $ALGoHelperPath = "$([System.IO.Path]::GetTempFileName()).ps1"
          $webClient = New-Object System.Net.WebClient
          $webClient.DownloadFile('https://raw.githubusercontent.com/microsoft/AL-Go-Actions/v7.2/AL-Go-Helper.ps1', $ALGoHelperPath)
          . $ALGoHelperPath
          DownloadAndImportBcContainerHelper
          Get-BcPublishedApps -environmentName "BC-SANDBOX-DEV"
